-- ACHTUNG: Löscht die alten Tabellen, um Platz für die neue Struktur zu machen
DROP TABLE IF EXISTS offerten;
DROP TABLE IF EXISTS projekte;
DROP TABLE IF EXISTS kunden;

-- 1. Tabelle 'kunden'
CREATE TABLE kunden (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  ort text,
  strasse text,
  plz text,
  telefon text,
  email text,
  status text DEFAULT 'Aktiv'::text
);

-- 2. Tabelle 'projekte'
CREATE TABLE projekte (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  kunden_id bigint REFERENCES kunden(id) ON DELETE CASCADE,
  name text NOT NULL,
  adresse text,
  status text DEFAULT 'Aktiv'::text
);

-- 3. Tabelle 'offerten'
CREATE TABLE offerten (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  projekt_id bigint REFERENCES projekte(id) ON DELETE CASCADE,
  kunden_id bigint REFERENCES kunden(id) ON DELETE CASCADE,
  total numeric,
  pdf_url text,
  status text DEFAULT 'Entwurf'::text,
  daten jsonb
);

-- 4. Tabelle 'katalog_kategorien'
CREATE TABLE katalog_kategorien (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sort_order integer DEFAULT 0
);

CREATE TABLE katalog_leistungen (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kategorie_id bigint REFERENCES katalog_kategorien(id) ON DELETE CASCADE,
  beschreibung text NOT NULL,
  einheit text,
  einzelpreis numeric,
  sort_order integer DEFAULT 0,
  ertragskonto text DEFAULT '3400 Dienstleistungserlöse'
);

-- Row Level Security (RLS) aktivieren
ALTER TABLE kunden ENABLE ROW LEVEL SECURITY;
ALTER TABLE projekte ENABLE ROW LEVEL SECURITY;
ALTER TABLE offerten ENABLE ROW LEVEL SECURITY;

-- Zugriffsrechte (Für Demo-Zwecke alles erlaubt, in Produktion später anpassen)
CREATE POLICY "Allow public read access on kunden" ON kunden FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on kunden" ON kunden FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on kunden" ON kunden FOR UPDATE USING (true);

CREATE POLICY "Allow public read access on projekte" ON projekte FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on projekte" ON projekte FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on projekte" ON projekte FOR UPDATE USING (true);

CREATE POLICY "Allow public read access on offerten" ON offerten FOR SELECT USING (true);
CREATE POLICY "Allow public insert access on offerten" ON offerten FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access on offerten" ON offerten FOR UPDATE USING (true);

ALTER TABLE katalog_kategorien ENABLE ROW LEVEL SECURITY;
ALTER TABLE katalog_leistungen ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all access on katalog_kategorien" ON katalog_kategorien FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all access on katalog_leistungen" ON katalog_leistungen FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- ERWEITERUNG: Zusätzliche Felder für CRM & Projektmanagement (ALTER TABLES)
-- Führe diesen Block aus, um bestehende Tabellen um neue Felder zu ergänzen.
-- ============================================================================

ALTER TABLE kunden 
ADD COLUMN IF NOT EXISTS firmenname text,
ADD COLUMN IF NOT EXISTS vorname text,
ADD COLUMN IF NOT EXISTS nachname text,
ADD COLUMN IF NOT EXISTS notizen text;

ALTER TABLE projekte
ADD COLUMN IF NOT EXISTS startdatum date,
ADD COLUMN IF NOT EXISTS enddatum date,
ADD COLUMN IF NOT EXISTS notizen text;

ALTER TABLE offerten
ADD COLUMN IF NOT EXISTS gueltig_bis date,
ADD COLUMN IF NOT EXISTS notizen text;

ALTER TABLE katalog_leistungen
ADD COLUMN IF NOT EXISTS ertragskonto text DEFAULT '3400 Dienstleistungserlöse';