-- ============================================================================
-- ATELIER 77 - TERMIN- & KALENDER-MODUL SCHEMA
-- ============================================================================
-- Führe dieses Skript im Supabase SQL Editor aus:
-- https://supabase.com/dashboard/project/fpfdlraqtqtcnmajrcyx/sql
-- ============================================================================

-- 1. Tabelle 'termine' anlegen
CREATE TABLE IF NOT EXISTS public.termine (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
  titel text NOT NULL,
  beschreibung text,
  datum date NOT NULL,
  end_datum date,
  startzeit text, -- z.B. '08:30'
  endzeit text,   -- z.B. '12:00'
  ganztaegig boolean DEFAULT false,
  typ text DEFAULT 'Montage'::text, -- 'Montage', 'Aufmass', 'Kundentermin', 'Lieferung', 'Abnahme', 'Intern', 'Urlaub', 'Sonstiges'
  status text DEFAULT 'Geplant'::text, -- 'Geplant', 'Bestätigt', 'In Durchführung', 'Erledigt', 'Abgesagt'
  projekt_id bigint REFERENCES public.projekte(id) ON DELETE SET NULL,
  kunden_id bigint REFERENCES public.kunden(id) ON DELETE SET NULL,
  ort text,
  farbe text,
  erstellt_von UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 2. Indizes für performante Kalenderabfragen
CREATE INDEX IF NOT EXISTS idx_termine_tenant_datum ON public.termine(tenant_id, datum);
CREATE INDEX IF NOT EXISTS idx_termine_projekt_id ON public.termine(projekt_id);
CREATE INDEX IF NOT EXISTS idx_termine_kunden_id ON public.termine(kunden_id);

-- 3. Trigger für automatisches Befüllen von tenant_id
CREATE OR REPLACE FUNCTION public.set_termine_tenant_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.tenant_id IS NULL THEN
    SELECT tenant_id INTO NEW.tenant_id FROM public.user_roles WHERE id = auth.uid();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_termine_tenant_id ON public.termine;
CREATE TRIGGER trg_termine_tenant_id
BEFORE INSERT ON public.termine
FOR EACH ROW EXECUTE FUNCTION public.set_termine_tenant_id();

-- 4. Row Level Security (RLS) aktivieren
ALTER TABLE public.termine ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies für Multi-Tenancy
DROP POLICY IF EXISTS "Users can view own tenant termine" ON public.termine;
CREATE POLICY "Users can view own tenant termine" ON public.termine
FOR SELECT USING (
  tenant_id = (SELECT tenant_id FROM public.user_roles WHERE id = auth.uid())
);

DROP POLICY IF EXISTS "Users can insert own tenant termine" ON public.termine;
CREATE POLICY "Users can insert own tenant termine" ON public.termine
FOR INSERT WITH CHECK (
  tenant_id = (SELECT tenant_id FROM public.user_roles WHERE id = auth.uid())
);

DROP POLICY IF EXISTS "Users can update own tenant termine" ON public.termine;
CREATE POLICY "Users can update own tenant termine" ON public.termine
FOR UPDATE USING (
  tenant_id = (SELECT tenant_id FROM public.user_roles WHERE id = auth.uid())
);

DROP POLICY IF EXISTS "Users can delete own tenant termine" ON public.termine;
CREATE POLICY "Users can delete own tenant termine" ON public.termine
FOR DELETE USING (
  tenant_id = (SELECT tenant_id FROM public.user_roles WHERE id = auth.uid())
);
